<a href="https://colab.research.google.com/github/jayanth940/Jayanth/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Pandas**

In [ ]:
import pandas as pd
import numpy as np

#### **Pandas Series (1D Data)**

In [ ]:
list1 = [10, 20, 30, 40, 50, 60]

In [ ]:
arr1 = np.array(list1)

In [ ]:
series = pd.Series(arr1)

In [ ]:
series[3]

np.int64(40)

In [ ]:
series[1:4] #[start_index : stop_index+1]

1    20
2    30
3    40
dtype: int64

In [ ]:
series[3] = 45

In [ ]:
series

0    10
1    20
2    30
3    45
4    50
5    60
dtype: int64

### **Pandas DataFrame (2D Data)**

In [ ]:
dict1 = {'Cust_id': [1,2,3,4,5],
         'Profit': [121, 876, 543, 678, 990],
         'Sales': [7564, 5342, 1298, 9021, 7789]}

In [ ]:
dict1

{'Cust_id': [1, 2, 3, 4, 5],
 'Profit': [121, 876, 543, 678, 990],
 'Sales': [7564, 5342, 1298, 9021, 7789]}

In [ ]:
df = pd.DataFrame(dict1)

In [ ]:
df

   Cust_id  Profit  Sales
0        1     121   7564
1        2     876   5342
2        3     543   1298
3        4     678   9021
4        5     990   7789

In [ ]:
market = pd.read_csv('market_fact.csv')

In [ ]:
market

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [ ]:
market.head() #print the top 5 rows of the data to have a quick look

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.27,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38

In [ ]:
market.head(100)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
95,Ord_5462,Prod_4,SHP_7632,Cust_1820,175.8565,0.03,10,-93.26,1.25,0.83
96,Ord_5489,Prod_17,SHP_7671,Cust_1820,754.9200,0.00,7,-129.57,19.99,0.52
97,Ord_5462,Prod_5,SHP_7631,Cust_1820,323.9600,0.07,40,-136.82,7.96,0.49
98,Ord_5481,Prod_15,SHP_7659,Cust_1820,2700.7800,0.06,29,-793.36,58.20,0.58
99,Ord_1638,Prod_5,SHP_5892,Cust_1433,755.1900,0.00,41,81.44,8.99,0.47

In [ ]:
market.tail() #print the bottom 5 rows of the data

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [ ]:
market.tail(100)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
8299,Ord_2074,Prod_3,SHP_2838,Cust_787,78.1700,0.01,21,-72.70,5.44,0.36
8300,Ord_2190,Prod_6,SHP_2986,Cust_787,23.2300,0.09,4,-19.06,6.72,0.40
8301,Ord_2707,Prod_5,SHP_3706,Cust_1025,267.0600,0.03,42,-96.95,5.22,0.60
8302,Ord_2707,Prod_6,SHP_3707,Cust_1025,449.7900,0.06,11,13.21,17.48,0.36
8303,Ord_2655,Prod_15,SHP_3632,Cust_1025,559.7500,0.07,4,-331.08,70.20,0.74
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [ ]:
market.shape  #print the number of rows and columns

(8399, 10)

In [ ]:
market.info() #print some basic information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ord_id               8399 non-null   object
 1   Prod_id              8399 non-null   object
 2   Ship_id              8399 non-null   object
 3   Cust_id              8399 non-null   object
 4   Sales                8399 non-null   float64
 5   Discount             8399 non-null   float64
 6   Order_Quantity       8399 non-null   int64
 7   Profit               8399 non-null   float64
 8   Shipping_Cost        8399 non-null   float64
 9   Product_Base_Margin  8336 non-null   float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.3+ KB

In [ ]:
market.isnull().sum() #print the total number of missing values column-wise

Ord_id                  0
Prod_id                 0
Ship_id                 0
Cust_id                 0
Sales                   0
Discount                0
Order_Quantity          0
Profit                  0
Shipping_Cost           0
Product_Base_Margin    63
dtype: int64

In [ ]:
market.isnull().sum(axis = 1) #print the total number of missing values row-wise

0       0
1       0
2       0
3       0
4       0
       ..
8394    0
8395    0
8396    0
8397    0
8398    0
Length: 8399, dtype: int64

In [ ]:
market.dtypes #print the datatype of values in each column

Ord_id                  object
Prod_id                 object
Ship_id                 object
Cust_id                 object
Sales                  float64
Discount               float64
Order_Quantity           int64
Profit                 float64
Shipping_Cost          float64
Product_Base_Margin    float64
dtype: object

In [ ]:
market.columns  #print the list of column names present in the dataframe

Index(['Ord_id', 'Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount',
       'Order_Quantity', 'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

### **Indexing and Slicing**

In [ ]:
market.head(100)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
95,Ord_5462,Prod_4,SHP_7632,Cust_1820,175.8565,0.03,10,-93.26,1.25,0.83
96,Ord_5489,Prod_17,SHP_7671,Cust_1820,754.9200,0.00,7,-129.57,19.99,0.52
97,Ord_5462,Prod_5,SHP_7631,Cust_1820,323.9600,0.07,40,-136.82,7.96,0.49
98,Ord_5481,Prod_15,SHP_7659,Cust_1820,2700.7800,0.06,29,-793.36,58.20,0.58
99,Ord_1638,Prod_5,SHP_5892,Cust_1433,755.1900,0.00,41,81.44,8.99,0.47

In [ ]:
market[100:501] #[start_index : stop_index + 1]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
100,Ord_1638,Prod_8,SHP_5892,Cust_1433,220.7900,0.00,7,-91.51,4.00,0.74
101,Ord_1638,Prod_7,SHP_2261,Cust_565,201.1400,0.08,37,-51.25,3.37,0.54
102,Ord_1557,Prod_2,SHP_2152,Cust_565,1736.5300,0.10,46,457.03,3.99,0.56
103,Ord_209,Prod_13,SHP_285,Cust_45,30.5100,0.09,11,-17.68,2.40,0.58
104,Ord_246,Prod_8,SHP_341,Cust_45,862.2000,0.10,29,-45.10,4.00,0.75
...,...,...,...,...,...,...,...,...,...,...
496,Ord_5310,Prod_13,SHP_7415,Cust_1776,70.3200,0.08,19,-56.07,4.17,0.59
497,Ord_5272,Prod_6,SHP_7361,Cust_1776,676.2400,0.05,25,219.78,5.86,0.39
498,Ord_5257,Prod_5,SHP_7340,Cust_1776,157.0300,0.07,7,13.21,5.08,0.41
499,Ord_5309,Prod_4,SHP_7413,Cust_1776,984.6315,0.00,20,-129.14,5.00,0.80
500,Ord_1127,Prod_3,SHP_1554,Cust_434,136.8500,0.01,14,-4.43,5.60,0.36

In [ ]:
market[100:501:5]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
100,Ord_1638,Prod_8,SHP_5892,Cust_1433,220.7900,0.00,7,-91.51,4.00,0.74
105,Ord_122,Prod_17,SHP_165,Cust_45,42.3100,0.06,2,-53.08,8.51,0.40
110,Ord_239,Prod_4,SHP_332,Cust_45,2157.3085,0.00,38,519.25,5.31,0.57
115,Ord_23,Prod_12,SHP_31,Cust_18,282.0700,0.03,39,140.01,0.49,0.38
120,Ord_5354,Prod_5,SHP_7480,Cust_1800,152.4400,0.08,20,-16.64,3.68,0.52
...,...,...,...,...,...,...,...,...,...,...
480,Ord_18,Prod_13,SHP_25,Cust_16,67.2400,0.06,23,4.90,0.93,0.54
485,Ord_33,Prod_4,SHP_43,Cust_16,1210.0515,0.04,11,-104.25,7.69,0.58
490,Ord_5256,Prod_13,SHP_7339,Cust_1772,56.7300,0.09,12,8.33,0.71,0.52
495,Ord_5310,Prod_6,SHP_7414,Cust_1776,134.3300,0.07,43,25.02,1.14,0.40
500,Ord_1127,Prod_3,SHP_1554,Cust_434,136.8500,0.01,14,-4.43,5.60,0.36

In [ ]:
market['Profit']  #select the profit column from market dataframe

0        -30.51
1          4.56
2       1148.90
3        729.34
4       1219.87
         ...
8394     374.63
8395     -74.03
8396     -70.85
8397     565.34
8398     131.39
Name: Profit, Length: 8399, dtype: float64

In [ ]:
market['Profit'].sum()  #print the total profit

np.float64(1521767.98)

In [ ]:
market[['Cust_id', 'Sales', 'Discount']]

        Cust_id      Sales  Discount
0     Cust_1818   136.8100      0.01
1     Cust_1818    42.2700      0.01
2     Cust_1818  4701.6900      0.00
3     Cust_1818  2337.8900      0.09
4     Cust_1818  4233.1500      0.08
...         ...        ...       ...
8394  Cust_1798  2841.4395      0.08
8395  Cust_1798   127.1600      0.10
8396  Cust_1798   243.0500      0.02
8397  Cust_1798  3872.8700      0.03
8398  Cust_1798   603.6900      0.00

[8399 rows x 3 columns]

In [ ]:
market[100:501, ['Cust_id', 'Sales', 'Discount']]

InvalidIndexError: (slice(100, 501, None), ['Cust_id', 'Sales', 'Discount'])

In [ ]:
market[5]

KeyError: 5

In [ ]:
market[[3, 56, 98, 567, 3421]]

KeyError: "None of [Index([3, 56, 98, 567, 3421], dtype='int64')] are in the [columns]"

### **Data Selection using `iloc` and `loc`**

#### **iloc** : index based selection of the data

In [ ]:
market.head(15)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
8,Ord_4725,Prod_13,SHP_6593,Cust_1641,162.0000,0.01,33,45.84,0.71,0.52
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.2200,0.07,8,-27.72,6.60,0.37
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
11,Ord_1925,Prod_6,SHP_2637,Cust_708,465.9000,0.05,38,79.34,4.86,0.38
12,Ord_2978,Prod_16,SHP_4112,Cust_1088,305.0500,0.04,27,23.12,3.37,0.57
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.9300,0.08,10,-317.48,36.09,0.77

In [ ]:
market.iloc[5]

Ord_id                  Ord_5446
Prod_id                   Prod_6
Ship_id                 SHP_7608
Cust_id                Cust_1818
Sales                     164.02
Discount                    0.03
Order_Quantity                23
Profit                    -47.64
Shipping_Cost               6.15
Product_Base_Margin         0.37
Name: 5, dtype: object

In [ ]:
market.iloc[[3, 65, 89, 769, 3421]]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
65,Ord_4547,Prod_6,SHP_6328,Cust_1474,23.44,0.05,3,-10.58,5.20,0.36
89,Ord_5355,Prod_1,SHP_7481,Cust_1802,123.85,0.09,16,-71.44,6.50,0.59
769,Ord_5187,Prod_17,SHP_7250,Cust_1746,15703.82,0.06,20,3055.72,16.06,0.56
3421,Ord_5285,Prod_5,SHP_7378,Cust_1787,1071.77,0.09,25,262.07,4.80,0.68

In [ ]:
market.iloc[3, 4]

np.float64(2337.89)

In [ ]:
market.iloc[100:501, [3,4,5]]

       Cust_id      Sales  Discount
100  Cust_1433   220.7900      0.00
101   Cust_565   201.1400      0.08
102   Cust_565  1736.5300      0.10
103    Cust_45    30.5100      0.09
104    Cust_45   862.2000      0.10
..         ...        ...       ...
496  Cust_1776    70.3200      0.08
497  Cust_1776   676.2400      0.05
498  Cust_1776   157.0300      0.07
499  Cust_1776   984.6315      0.00
500   Cust_434   136.8500      0.01

[401 rows x 3 columns]

#### **loc** : label/text/name based data selection

In [ ]:
market.loc[100:501, ['Cust_id', 'Sales', 'Discount']]

       Cust_id      Sales  Discount
100  Cust_1433   220.7900      0.00
101   Cust_565   201.1400      0.08
102   Cust_565  1736.5300      0.10
103    Cust_45    30.5100      0.09
104    Cust_45   862.2000      0.10
..         ...        ...       ...
497  Cust_1776   676.2400      0.05
498  Cust_1776   157.0300      0.07
499  Cust_1776   984.6315      0.00
500   Cust_434   136.8500      0.01
501   Cust_434    12.7400      0.05

[402 rows x 3 columns]

### **Data Selection using conditions**

In [ ]:
market.head(15)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
8,Ord_4725,Prod_13,SHP_6593,Cust_1641,162.0000,0.01,33,45.84,0.71,0.52
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.2200,0.07,8,-27.72,6.60,0.37
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
11,Ord_1925,Prod_6,SHP_2637,Cust_708,465.9000,0.05,38,79.34,4.86,0.38
12,Ord_2978,Prod_16,SHP_4112,Cust_1088,305.0500,0.04,27,23.12,3.37,0.57
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.9300,0.08,10,-317.48,36.09,0.77

In [ ]:
market['Profit'] < 0   #mark True for the rows which has negative profit values

0        True
1       False
2       False
3       False
4       False
        ...
8394    False
8395     True
8396     True
8397    False
8398    False
Name: Profit, Length: 8399, dtype: bool

In [ ]:
market[market['Profit'] < 0]  #select all the rows which has negative profit values

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.810,0.01,23,-30.51,3.60,0.56
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.020,0.03,23,-47.64,6.15,0.37
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.220,0.07,8,-27.72,6.60,0.37
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.248,0.10,15,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.930,0.08,10,-317.48,36.09,0.77
...,...,...,...,...,...,...,...,...,...,...
8388,Ord_4424,Prod_1,SHP_6165,Cust_1519,994.040,0.03,10,-335.06,35.00,NaN
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,316.990,0.04,47,-276.54,8.37,0.58
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,181.500,0.08,43,-6.24,2.50,0.37
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.160,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.050,0.02,39,-70.85,5.35,0.40

In [ ]:
market['Sales'] > 100

0        True
1       False
2        True
3        True
4        True
        ...
8394     True
8395     True
8396     True
8397     True
8398     True
Name: Sales, Length: 8399, dtype: bool

In [ ]:
market[market['Sales'] > 100]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [ ]:
(market['Profit'] < 0) & (market['Sales'] > 100)

0        True
1       False
2       False
3       False
4       False
        ...
8394    False
8395     True
8396     True
8397    False
8398    False
Length: 8399, dtype: bool

In [ ]:
market[(market['Profit'] < 0) & (market['Sales'] > 100)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.810,0.01,23,-30.51,3.60,0.56
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.020,0.03,23,-47.64,6.15,0.37
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.248,0.10,15,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.930,0.08,10,-317.48,36.09,0.77
15,Ord_2280,Prod_5,SHP_3114,Cust_839,460.690,0.06,48,-103.48,7.29,0.45
...,...,...,...,...,...,...,...,...,...,...
8388,Ord_4424,Prod_1,SHP_6165,Cust_1519,994.040,0.03,10,-335.06,35.00,NaN
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,316.990,0.04,47,-276.54,8.37,0.58
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,181.500,0.08,43,-6.24,2.50,0.37
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.160,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.050,0.02,39,-70.85,5.35,0.40

In [ ]:
market.loc[(market['Profit'] < 0) & (market['Sales'] > 100), ['Cust_id', 'Sales', 'Discount']]

        Cust_id     Sales  Discount
0     Cust_1818   136.810      0.01
5     Cust_1818   164.020      0.03
13     Cust_839  3364.248      0.10
14     Cust_839  1410.930      0.08
15     Cust_839   460.690      0.06
...         ...       ...       ...
8388  Cust_1519   994.040      0.03
8390  Cust_1798   316.990      0.04
8392  Cust_1798   181.500      0.08
8395  Cust_1798   127.160      0.10
8396  Cust_1798   243.050      0.02

[3190 rows x 3 columns]

In [ ]:
market[(market['Profit'] < 0) | (market['Sales'] > 100)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [ ]:
and : &
or : |
not : ~

In [ ]:
market[~(market['Profit'] < 0)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
...,...,...,...,...,...,...,...,...,...,...
8391,Ord_5435,Prod_4,SHP_7594,Cust_1798,1991.8985,0.07,20,88.36,7.69,0.58
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,356.7200,0.07,9,12.61,1.99,0.44
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

### **Sorting the DataFrames**

In [ ]:
dict1 = {'Cust_id': [1,2,3,4,5],
         'Profit': [121, 876, 543, 678, 990],
         'Sales': [7564, 5342, 1298, 9021, 7789]}

In [ ]:
df = pd.DataFrame(dict1)

In [ ]:
df

   Cust_id  Profit  Sales
0        1     121   7564
1        2     876   5342
2        3     543   1298
3        4     678   9021
4        5     990   7789